version: 2

sources:
  - name: public           # the Postgres schema
    tables:
      - name: stg_users
      - name: stg_posts
      - name: stg_comments
      - name: stg_todos
models:
  - name: stg_users_clean
    description: "Standardised users"
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: stg_posts_clean
    description: "Clean posts"
    columns:
      - name: post_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]

  - name: stg_comments_clean
    description: "Clean post comments"

  - name: stg_todos_clean
    description: "Clean user todos"

  - name: dim_user
    description: "Master dimension table for user details"
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: fact_posts
    description: "Posts authored by users"

  - name: fact_comments
    description: "Comments on posts"

  - name: fact_todos
    description: "Todo items per user"
